apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvn-repo
spec:
  selector:
    matchLabels:
      app: mvn-repo
  template:
    metadata:
      labels:
        app: mvn-repo
    spec:
      volumes:
      - name: mvn-repo-data
        persistentVolumeClaim:
          claimName: mvn-repo-data
      - name: mvn-repo-keystore
        secret:
          secretName: mvn-repo-keystore
      containers:
      - name: mvn-repo
        image: virtuslab/scala-community-build-mvn-repo:v0.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: mvn-repo-data
          mountPath: /mvn-repo/upload-dir
        - name: mvn-repo-keystore
          mountPath: /mvn-repo/keystore
          readOnly: true
        env:
        - name: MVN_REPO_KEY_STORE
          value: /mvn-repo/keystore/mvn-repo.p12
        - name: MVN_REPO_KEY_STORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mvn-repo-passwords
              key: keystore-password
        - name: MVN_REPO_KEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mvn-repo-passwords
              key: keystore-password
---
apiVersion: v1
kind: Service
metadata:
  name: mvn-repo
spec:
  type: ClusterIP
  selector:
    app: mvn-repo
  ports:
  - protocol: TCP
    port: 8081
